version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
      terraform: 1.0
  pre_build:
    commands:
      - echo "Pre-build phase"
  build:
    commands:
      - echo "Build phase"
      - git clone --branch legacy https://github.com/Aj7Ay/chatbot-ui.git
      - cd chatbot-ui
      - terraform --version
      - cd ..
      - cd Eks-terraform
      - terraform init
      - terraform validate
      - terraform plan
      # For apply or destroy, set the action variable as 'apply' or 'destroy' before executing
      - terraform ${action} --auto-approve
