version: 0.2

env:
  tools:
    jdk: 'jdk17'
    nodejs: 'node18'
  variables:
    SCANNER_HOME: 'http://54.174.176.30:9000'
  parameter-store: 
    DOCKER_USER: "/fbn/dev/env"
    DOCKER_PASSWORD: "/fbn/dev/env"
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Install phase"
      - npm install
  pre_build: 
    commands: 
      - DOCKER_USER=somanaboina
      - DOCKER_PASSWORD=Welcome@123
      - echo Logging in to Docker Hub...
      - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USER --password-stdin
  build:
    commands:
      - echo "Build phase"
      # Perform SonarQube analysis
      - $SCANNER_HOME/bin/sonar-scanner -Dsonar.projectName=Chatbot -Dsonar.projectKey=Chatbot
      # Perform OWASP Dependency Check
      - dependency-check --scan ./ --disableYarnAudit --disableNodeAudit --format XML --out .
      # Perform TRIVY FS SCAN
      - trivy fs . > trivyfs.json
      # Build Docker image
      - docker build -t chatbot .
      # Tag Docker image
      - docker tag chatbot somanaboina/chatbot:latest
  post_build:
    commands:
      - echo "Post-build phase"
      # Push Docker image to Docker Hub
      - docker push somanaboina/chatbot:latest
      # Perform TRIVY scan on Docker image
      - trivy image somanaboina/chatbot:latest > trivy.json
      # Remove existing container
      - docker stop chatbot || true
      - docker rm chatbot || true
      # Deploy to container
      - docker run -d --name chatbot -p 3000:3000 somanaboina/chatbot:latest
